### ISSUE TITLE
gazebo cannot load when running the launch file

### ISSUE THREAD

**Issue by sjtuhjw** [NKU-MobFly-Robotics/LRAE#10]
Dear Dr. Bi, thank you for your wonderful work！ The gazebo cannot load the world when running the launch file, although I have download [gazebo_models](https://github.com/osrf/gazebo_models) to the directory ~/.gazebo/models as you requested.

**Comment by qingchen-bi** [comment]
Can you provide detailed terminal information and environment information, or try running other scenarios?

**Comment by sjtuhjw** [comment]
Thank you for your reply. I have found the solution. The related model brick_wall_hole_*  are missing in ~/.gazebo/models. After I installed these missing models, everything was normal.
