### ISSUE TITLE
how to replace scenes to other world file &  confusion for a code snippet

### ISSUE THREAD

**Issue by Jaqen81** [NKU-MobFly-Robotics/LRAE#5]
Hi QingChen, 
Thanks for your inspiring work! I can correctly run commands for four scenes that you provided but got a problem with replacing the current scene with another world file. I've done:
1. add world file in `workspace/LRAE_ws/src/LRAE/simworld/worlds`
2. created another launch file in `workspace/LRAE_ws/src/LRAE/fitplane/launch/launch` called simulation_inspection.launch and running it successfully with correct world image shows up
3. created another launch file in `workspace/LRAE_ws/src/LRAE/lrae_planner/launch` called exploration_inspection.launch
The problems I've encountered:
1. after I ran `source devel/setup.bash && roslaunch lrae_planner exploration_inspection.launch` in the terminal, output error is:
```
root@dcfacbe521d9:~/LRAE_ws# source devel/setup.bash && roslaunch lrae_planner exploration_inspection.launch
... logging to /root/.ros/log/d16b21b8-9b84-11ef-b0c2-0242ac1a0004/roslaunch-dcfacbe521d9-2304427.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/root/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

started roslaunch server http://dcfacbe521d9:44079/

SUMMARY
========

PARAMETERS
 * /exploration_map_merge/debug: True
 * /exploration_map_merge/map_h: 37400
 * /exploration_map_merge/map_w: 37400
 * /exploration_map_merge/mapinitox: -5.0
 * /exploration_map_merge/mapinitoy: -5.0
 * /exploration_map_merge/merge_size: 9.0
 * /exploration_map_merge/safe_obs_dis: 1.0
 * /localPlanner/adjacentRange: 4.25
 * /localPlanner/autonomyMode: True
 * /localPlanner/autonomySpeed: 1.0
 * /localPlanner/checkObstacle: True
 * /localPlanner/checkRotObstacle: False
 * /localPlanner/costHeightThre: 0.5
 * /localPlanner/costScore: 0.02
 * /localPlanner/dirThre: 90.0
 * /localPlanner/dirToVehicle: False
 * /localPlanner/dirWeight: 0.02
 * /localPlanner/goalClearRange: 0.5
 * /localPlanner/goalX: 0.0
 * /localPlanner/goalY: 0.0
 * /localPlanner/groundHeightThre: 0.1
 * /localPlanner/joyToCheckObstacleDelay: 5.0
 * /localPlanner/joyToSpeedDelay: 2.0
 * /localPlanner/laserVoxelSize: 0.05
 * /localPlanner/maxRelZ: 0.25
 * /localPlanner/maxSpeed: 1.0
 * /localPlanner/minPathRange: 1.0
 * /localPlanner/minPathScale: 0.75
 * /localPlanner/minRelZ: -0.5
 * /localPlanner/obstacleHeightThre: 0.3
 * /localPlanner/pathCropByGoal: True
 * /localPlanner/pathFolder: /root/LRAE_ws/src...
 * /localPlanner/pathRangeBySpeed: True
 * /localPlanner/pathRangeStep: 0.5
 * /localPlanner/pathScale: 1.25
 * /localPlanner/pathScaleBySpeed: True
 * /localPlanner/pathScaleStep: 0.25
 * /localPlanner/pointPerPathThre: 2
 * /localPlanner/sensorOffsetX: 0
 * /localPlanner/sensorOffsetY: 0
 * /localPlanner/terrainVoxelSize: 0.1
 * /localPlanner/twoWayDrive: True
 * /localPlanner/useCost: False
 * /localPlanner/useTerrainAnalysis: True
 * /localPlanner/vehicleLength: 0.6
 * /localPlanner/vehicleWidth: 0.6
 * /lrae_planner_node/angle_pen: 0.45
 * /lrae_planner_node/limit_max_square: False
 * /lrae_planner_node/minrange: 30.0
 * /lrae_planner_node/unknown_num_thre: 300
 * /lrae_planner_node/update_cen_thre: 6
 * /lrae_planner_node/use_go_end_nearest: True
 * /pathFollower/autonomyMode: True
 * /pathFollower/autonomySpeed: 1.0
 * /pathFollower/dirDiffThre: 0.1
 * /pathFollower/inclRateThre: 120.0
 * /pathFollower/inclThre: 45.0
 * /pathFollower/joyToSpeedDelay: 2.0
 * /pathFollower/lookAheadDis: 0.5
 * /pathFollower/maxAccel: 2.0
 * /pathFollower/maxSpeed: 1.0
 * /pathFollower/maxYawRate: 90.0
 * /pathFollower/noRotAtGoal: True
 * /pathFollower/noRotAtStop: False
 * /pathFollower/pubSkipNum: 1
 * /pathFollower/sensorOffsetX: 0
 * /pathFollower/sensorOffsetY: 0
 * /pathFollower/slowDwnDisThre: 0.85
 * /pathFollower/slowRate1: 0.25
 * /pathFollower/slowRate2: 0.5
 * /pathFollower/slowTime1: 2.0
 * /pathFollower/slowTime2: 2.0
 * /pathFollower/stopDisThre: 0.2
 * /pathFollower/stopTime: 5.0
 * /pathFollower/stopYawRateGain: 7.5
 * /pathFollower/switchTimeThre: 1.0
 * /pathFollower/twoWayDrive: True
 * /pathFollower/useInclRateToSlow: False
 * /pathFollower/useInclToStop: False
 * /pathFollower/yawRateGain: 7.5
 * /rosdistro: noetic
 * /rosversion: 1.17.0

NODES
  /
    exploration_map_merge (lrae_planner/exploration_map_merge)
    gen_local_goal_node (gen_local_goal/gen_local_goal_node)
    localPlanner (local_planner/localPlanner)
    lrae_planner_node (lrae_planner/lrae_planner_node)
    pathFollower (local_planner/pathFollower)
    vehicleTransPublisher (tf/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[lrae_planner_node-1]: started with pid [2304441]
process[exploration_map_merge-2]: started with pid [2304442]
process[gen_local_goal_node-3]: started with pid [2304443]
process[localPlanner-4]: started with pid [2304445]
process[pathFollower-5]: started with pid [2304450]
process[vehicleTransPublisher-6]: started with pid [2304455]

Reading path files.

Initialization complete.

[ERROR] [1730818029.394283484, 159.206000000]: "map" passed to lookupTransform argument target_frame does not exist. 
[exploration_map_merge-2] process has died [pid 2304442, exit code -11, cmd /root/LRAE_ws/devel/lib/lrae_planner/exploration_map_merge __name:=exploration_map_merge __log:=/root/.ros/log/d16b21b8-9b84-11ef-b0c2-0242ac1a0004/exploration_map_merge-2.log].
log file: /root/.ros/log/d16b21b8-9b84-11ef-b0c2-0242ac1a0004/exploration_map_merge-2*.log
```

I've changes params in exploration_inspection.launch:    
```
 <param name="map_w" type="int" value="37400" />
    <param name="map_h" type="int" value="37400" />
```
What else parameters should I change in order to run the algorithm? 

---------------------dividing line-----------------------------

also another confusion about a code snippet when I was trying to understand the file 'exploration_map_merge.cpp', line 73 and 74,
https://github.com/NKU-MobFly-Robotics/LRAE/blob/78febcf218b1676bf6205b60410a68f6031fdd0b/lrae_planner/src/exploration_map_merge.cpp#L73C1-L74C118 
the screenshot are below:
![20241105debug1](https://github.com/user-attachments/assets/695daa3d-a827-473b-9eb2-2b0cdb9ae090)
![20241105debug2](https://github.com/user-attachments/assets/3cbf978c-fa22-449f-aa3e-415e0f40d4df)
why the value of "globalMapData.info.height" and "globalMapData.info.width" haven't been assigned.

Looking forward for your reply, thanks!

**Comment by qingchen-bi** [comment]
We have updated the code for other scenes, please use the latest code.

**Comment by Jaqen81** [comment]
Thanks, solved it by changing the params you mentioned.

**Comment by Jaqen81** [comment]
Hi, I'll just answer this here so that other people could see this answer.

Let's take a look at the diagram in readme file. Robot's position shows as the yellow round point, also x positive axis and y positive axis as the arrow indicated. 

The orange box around the robot shows the exploration range, with four parameters 'ex_robot_front', 'ex_robot_back', 'ex_robot_left', 'ex_robot_right' to define the exploration range. 

The red box outside of the orange box shows the whole map's range, with four parameters 'map_w' 'map_h' to define the range and the other two parameters 'mapinitox' and 'mapinitoy' to difine the map origin coordinates. 

All you need to do is change eight coordinates above metioned, **to make sure your exploration range less than map range all the way from start to end during exploration process**. You might need to approximate the map size and change params accordingly. Also its better for robot to face toward x positive axis to start explore.  

If it still doesn't work after you changed the params, please paste the code nippet and the complete output with it, we could further discuss this.

**Comment by Jaqen81** [comment]
I noticed that your robot start position is quite close to boarder line, guess this could be the problem of start point position. You might want to modify 'mapinitox' and 'mapinitoy' (eg. from -10 -10 to -50 -50)to change the relative position of global map with initial exploration area. To make sure the global map fully cover exploration range from the moment it started.

mal4a/mal4a-ofx#50

**Comment by 1461891375** [comment]
> I noticed that your robot start position is quite close to boarder line, guess this could be the problem of start point position. You might want to modify 'mapinitox' and 'mapinitoy' (eg. from -10 -10 to -50 -50)to change the relative position of global map with initial exploration area. To make sure the global map fully cover exploration range from the moment it started.
> 
> [ml4a/ml4a-ofx#50](https://github.com/ml4a/ml4a-ofx/issues/50)
