### ISSUE TITLE
error:No p gain specified for pid.

### ISSUE THREAD

**Issue by yinxiaomao** [NKU-MobFly-Robotics/LRAE#7]
[ERROR] [1732005002.203209, 1730.605000]: Spawn service failed. Exiting.
[spawn_scout_model-4] process has died [pid 7716, exit code 1, cmd /opt/ros/noetic/lib/gazebo_ros/spawn_model -x -14 -y -14 -z 0.3 -Y 0.0 -unpause -urdf -param robot_description -model scout/ __name:=spawn_scout_model __log:=/home/yxs/.ros/log/0cdb33de-a650-11ef-b6af-5daec9b6eb95/spawn_scout_model-4.log].
log file: /home/yxs/.ros/log/0cdb33de-a650-11ef-b6af-5daec9b6eb95/spawn_scout_model-4*.log

[ERROR] [1732005004.933909212, 1730.605000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/front_right_wheel
[ERROR] [1732005004.934452644, 1730.605000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/front_left_wheel
[ERROR] [1732005004.934874670, 1730.605000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/rear_left_wheel
[ERROR] [1732005004.935323091, 1730.605000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/rear_right_wheel

when I run "source devel/setup.bash && roslaunch fitplane simulation_scene1.launch",the above error occurred. What should I do to solve this error.
Thank you!

**Comment by qingchen-bi** [comment]
Is your ROS version Noetic?     
In addition，please ignore the "no p gain" error.

**Comment by yinxiaomao** [comment]
This issue is caused by the failure to execute the following command:
“In addition, we recommend that you download [gazebo_models](https://github.com/osrf/gazebo_models) to the directory ~/.gazebo/models.”

**Comment by qingchen-bi** [comment]
Even if this error occurs, the gazebo can still be started, the robot model can still be loaded, and RVIZ will have a point cloud map. You can ignore the error and run the second launch file to see if the robot can start exploring.
If the robot can explore, you don't have to worry about the problem.
