### ISSUE TITLE
Gazebo needs to download models every time it starts, why is that, and where are the models downloaded from?

### ISSUE THREAD

**Issue by howthep** [NKU-MobFly-Robotics/LRAE#8]
I’m encountering an issue where every time I start Gazebo, it needs to download models, which takes around 10 minutes. I’m not sure why this is happening. Can anyone tell me where the models used by Gazebo are being downloaded from? Is there a way to avoid downloading them every time?

I’ve already checked the model paths in Gazebo and verified that my network connection is fine. Is there any way to configure or cache these models to prevent repeated downloads?

Thanks!

**Comment by qingchen-bi** [comment]
https://github.com/qingchen-bi/FAEL-Noetic?tab=readme-ov-file#prerequisites

**Comment by howthep** [comment]
I have downloaded all models from https://github.com/osrf/gazebo_models, and put them in ~/.gazebo/models, but the problem still exists. Maybe there are some models from other source?

**Comment by qingchen-bi** [comment]
Open the terminal and enter the 'gazebo' command directly. Will this problem occur?

**Comment by howthep** [comment]
directly open gazebo, the problem won't occur

**Comment by qingchen-bi** [comment]
This problem has not been encountered. The items in the world are from the gazebo model library. If you want to open quickly, it is recommended to run the spawn_car.launch file, and then wait for the world to open, delete all items in the world, leaving only rough terrain, and then save the world, next time launch the world without other items, see if there is still this problem.

**Comment by howthep** [comment]
I delete all items whose names start with "brick," which should resolve the problem. Thank you for your help!
